[package]
name = "gblock"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"]}
chrono = "0.4.39"
sha256 = "1.5.0"
tokio = { version = "1.43.0", features = ["full"] }
tokio-util = "0.6"
